### ISSUE TITLE
roachtest: port decommission/mixed-versions to new mixed-version framework

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#110531]
See the parent issue [1] for details.

[1] https://github.com/cockroachdb/cockroach/issues/110528

**Comment by renatolabs** [comment]
FYI, I'm adding back the GA-blocker on these issues because 1) it has been applied on similar issues for other teams (most of which have already addressed their issues) and 2) it is part of the exit criteria for CY, so it would be nice to get them addressed in time for 23.2.

We can re-evaluate if KV has found no time to work on them by GA time.

**Comment by arulajmani** [comment]
I'm going to remove the GA-blocker label for now. There's a few other legit ones on my plate and I don't want us to hold the RC up for this. I'll still get to it in the very near term.
