### ISSUE TITLE
TPCC import succeeds, while consistency checks sometimes fail

### ISSUE THREAD

**Issue by eivanov89** [cockroachdb/cockroach#110738]
**Describe the problem**

I try to import initial TPC-C data.

```
cockroach workload fixtures import tpcc --warehouses=13000 'postgres://root@host:26257?sslmode=disable'

I230915 14:37:47.148627 1 ccl/workloadccl/fixture.go:315  [-] 1  starting import of 9 tables
I230915 14:37:49.950348 108 ccl/workloadccl/fixture.go:492  [-] 2  imported 705 KiB in warehouse table (13000 rows, 0 index entries, took 2.622700443s, 0.26 MiB/s)
I230915 14:37:51.202532 109 ccl/workloadccl/fixture.go:492  [-] 3  imported 13 MiB in district table (130000 rows, 0 index entries, took 3.874756765s, 3.34 MiB/s)
I230915 14:37:52.557898 226 ccl/workloadccl/fixture.go:492  [-] 4  imported 7.9 MiB in item table (100000 rows, 0 index entries, took 5.229539536s, 1.50 MiB/s)
I230915 14:38:32.296802 113 ccl/workloadccl/fixture.go:492  [-] 5  imported 1.7 GiB in new_order table (117000000 rows, 0 index entries, took 44.968524969s, 39.63 MiB/s)
I230915 14:43:16.869316 112 ccl/workloadccl/fixture.go:492  [-] 6  imported 21 GiB in order table (390000000 rows, 390000000 index entries, took 5m29.541104727s, 65.95 MiB/s)
I230915 14:44:10.181317 111 ccl/workloadccl/fixture.go:492  [-] 7  imported 28 GiB in history table (390000000 rows, 0 index entries, took 6m22.853216195s, 76.12 MiB/s)
I230915 14:49:05.337496 110 ccl/workloadccl/fixture.go:492  [-] 8  imported 225 GiB in customer table (390000000 rows, 390000000 index entries, took 11m18.009532307s, 340.00 MiB/s)
I230915 14:53:58.334377 227 ccl/workloadccl/fixture.go:492  [-] 9  imported 392 GiB in stock table (1300000000 rows, 0 index entries, took 16m11.005846138s, 413.32 MiB/s)
I230915 14:56:16.755741 228 ccl/workloadccl/fixture.go:492  [-] 10  imported 225 GiB in order_line table (3899967475 rows, 0 index entries, took 18m29.427167889s, 207.68 MiB/s)
I230915 14:56:16.812441 1 ccl/workloadccl/fixture.go:323  [-] 11  imported 894 GiB bytes in 9 tables (took 18m29.663295738s, 824.53 MiB/s)
I230915 14:56:19.290831 1 ccl/workloadccl/cliccl/fixtures.go:343  [-] 12  fixture is restored; now running consistency checks (ctrl-c to abort)
I230915 14:56:19.504132 1 workload/tpcc/tpcc.go:517  [-] 13  check 3.3.2.1 took 213.183355ms
I230915 14:58:37.656937 1 workload/tpcc/tpcc.go:517  [-] 14  check 3.3.2.2 took 2m18.152599629s
I230915 14:59:00.109822 1 workload/tpcc/tpcc.go:517  [-] 15  check 3.3.2.3 took 22.452724373s

I230915 15:11:48.106174 1 workload/tpcc/tpcc.go:517  [-] 16  check 3.3.2.4 took 12m47.996230562s
Error: check failed: 3.3.2.4: at 1694789940110274588.0000000000: length of order.sum(o_ol_cnt) != order_line.count(*)
```

Later I tried to do a quick check on my own:

```
root@localhost:26257/defaultdb> select sum(o_ol_cnt) from tpcc.order;
     sum
--------------
  3899967475
(1 row)

Time: 97.993s total (execution 97.992s / network 0.001s)

root@localhost:26257/defaultdb> select count(*) from tpcc.order_line ;
    count
--------------
  3899967475
(1 row)

Time: 320.052s total (execution 320.052s / network 0.001s)

```

The check is not per warehous/district though, but total number of order lines is correct.

**Environment:**
 - v23-1-9
 - Ubuntu 20.04

**Additional context**

My colleague also faced with import issues:
`Error: check failed: 3.3.2.7: pq: batch timestamp 1690649337.212712683,0 must be after replica GC threshold 1690649369.613864206,0 `

Jira issue: CRDB-31582

**Comment by cucaroach** [comment]
Possibly fixed by: https://github.com/cockroachdb/cockroach/pull/102081

Backport in progress.

**Comment by yuzefovich** [comment]
Backports have been merged, should we close this as dup of #102004 then?

**Comment by yuzefovich** [comment]
Closing as a dup of #102004 - please use `cockroach-v23.1.12` when it comes out, it should have this fixed.

**Comment by eivanov89** [comment]
It looks like the issue is still there in 23.2.2.linux-amd64:
```bash
> ./cockroach workload fixtures import tpcc --warehouses=15000 'postgres://root@ydb-000.net:26257?sslmode=disable' 
I240328 14:22:53.233733 1 ccl/workloadccl/fixture.go:315  [-] 1  starting import of 9 tables
I240328 14:22:55.463966 178 ccl/workloadccl/fixture.go:492  [-] 2  imported 799 KiB in warehouse table (15000 rows, 0 index entries, took 2.038001211s, 0.38 MiB/s)
I240328 14:22:55.529018 179 ccl/workloadccl/fixture.go:492  [-] 3  imported 15 MiB in district table (150000 rows, 0 index entries, took 2.102996028s, 7.03 MiB/s)
I240328 14:22:57.709862 184 ccl/workloadccl/fixture.go:492  [-] 4  imported 7.9 MiB in item table (100000 rows, 0 index entries, took 4.283678825s, 1.84 MiB/s)
I240328 14:23:52.124932 183 ccl/workloadccl/fixture.go:492  [-] 5  imported 2.0 GiB in new_order table (135000000 rows, 0 index entries, took 58.698756315s, 35.04 MiB/s)
I240328 14:27:29.544465 181 ccl/workloadccl/fixture.go:492  [-] 6  imported 32 GiB in history table (450000000 rows, 0 index entries, took 4m36.118350398s, 120.35 MiB/s)
I240328 14:30:25.943313 182 ccl/workloadccl/fixture.go:492  [-] 7  imported 24 GiB in order table (450000000 rows, 450000000 index entries, took 7m32.517195543s, 55.42 MiB/s)
I240328 14:40:54.936397 180 ccl/workloadccl/fixture.go:492  [-] 8  imported 259 GiB in customer table (450000000 rows, 450000000 index entries, took 18m1.510345718s, 245.15 MiB/s)
I240328 14:46:45.142326 185 ccl/workloadccl/fixture.go:492  [-] 9  imported 452 GiB in stock table (1500000000 rows, 0 index entries, took 23m51.716060829s, 323.45 MiB/s)
I240328 14:48:33.873420 186 ccl/workloadccl/fixture.go:492  [-] 10  imported 260 GiB in order_line table (4500037649 rows, 0 index entries, took 25m40.447142136s, 172.83 MiB/s)
I240328 14:48:33.925833 1 ccl/workloadccl/fixture.go:323  [-] 11  imported 1.0 TiB bytes in 9 tables (took 25m40.691943606s, 684.67 MiB/s)
I240328 14:48:37.084329 1 ccl/workloadccl/cliccl/fixtures.go:343  [-] 12  fixture is restored; now running consistency checks (ctrl-c to abort)
I240328 14:48:37.331713 1 workload/tpcc/tpcc.go:512  [-] 13  check 3.3.2.1 took 246.727219ms
I240328 14:49:25.135414 1 workload/tpcc/tpcc.go:512  [-] 14  check 3.3.2.2 took 47.803610613s
I240328 14:49:37.298711 1 workload/tpcc/tpcc.go:512  [-] 15  check 3.3.2.3 took 12.163119614s
I240328 14:58:31.715096 1 workload/tpcc/tpcc.go:512  [-] 16  check 3.3.2.4 took 8m54.416300391s
I240328 15:02:47.279255 1 workload/tpcc/tpcc.go:512  [-] 17  check 3.3.2.5 took 4m15.564065718s
I240328 15:14:55.097640 1 workload/tpcc/tpcc.go:512  [-] 18  check 3.3.2.7 took 12m7.818281831s
Error: check failed: 3.3.2.7: pq: batch timestamp 1711638167.280192337,0 must be after replica GC threshold 1711638241.952003698,0
```

@yuzefovich could you please reopen?

**Comment by yuzefovich** [comment]
This error is different from the original one you reported. We track this issue in #120897 - please feel free to follow that issue for updates.

**Comment by yuzefovich** [comment]
Or actually, this seems a bit different from #120897, let's track it here.

**Comment by yuzefovich** [comment]
Still, the fix to the issue is likely to be the same as to #120897. In the mean time, you can try increasing GC TTL for the newly-imported tables.
