### ISSUE TITLE
roachtest: stability problems during tpcc-{5,10,20}k on {6,12,24} nodes

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31409]
**Describe the problem**

Dead node with 9k underreplicated ranges when running tpcc 

**To Reproduce**

Modified to use roachtest from 2 days ago:

Modified test to use partitioning and 6 nodes:

```diff
@@ -675,11 +675,12 @@ func registerTPCCBench(r *registry) {
                        // StoreDirVersion: "2.0-5",
                },
                {
-                       Nodes: 3,
+                       Nodes: 6,
                        CPUs:  16,
 
-                       LoadWarehouses: 2000,
-                       EstimatedMax:   1300,
+                       LoadWarehouses: 5000,
+                       EstimatedMax:   3000,
+                       LoadConfig:     singlePartitionedLoadgen,
                },
```

Ran:

`bin/roachtest bench '^tpccbench/nodes=6/cpu=16/partition$$' --wipe=false --user=andy`

**Expected behavior**
No dead nodes

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/22278911/46983937-c9026900-d0b0-11e8-8590-5621617c5bcd.png)

**Environment:**
 - CockroachDB version 2.1 Beta 1008
 
Dead node logs:
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480879/cockroach.log)

**Comment by petermattis** [comment]
Which cluster is this? 

PS You grabbed the nodes for `n5`, not `n3`. The confusion between roachprod indexes and node IDs strikes again.

**Comment by awoods187** [comment]
andy-1539640859-tpccbench-nodes-6-cpu-16-partition

**Comment by petermattis** [comment]
It looks like the cluster has been wiped.

**Comment by awoods187** [comment]
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480909/cockroach.log)

**Comment by petermattis** [comment]
`n3` hit an OOM: `fatal error: runtime: out of memory`. The previous `runtime.go` message shows:

```
I181015 23:09:34.905569 360 server/status/runtime.go:465  [n3] runtime stats: 13 GiB RSS, 348 goroutines, 7.0 GiB/1.4
GiB/8.7 GiB GO alloc/idle/total, 3.6 GiB/4.4 GiB CGO alloc/total, 98011.8 CGO/sec, 59.0/34.5 %(u/s)time, 0.0 %gc (0x),
 258 MiB/6.7 MiB (r/w)net
```

Some sort of memory leak was occurring only on `n3`:

<img width="408" alt="screen shot 2018-10-15 at 7 58 56 pm" src="https://user-images.githubusercontent.com/6201335/46984763-d7eb1a80-d0b4-11e8-81c4-28b76b5e5d44.png">

**Comment by petermattis** [comment]
I'm not seeing anything interesting in the logs, but I don't have time to do a thorough check right now.

**Comment by tschottdorf** [comment]
As far as timing goes, the test runs from ~10pm to ~11pm. Here's the number of Raft snapshots within each minute:

```
$ rg --no-line-number 'applying Raft snapshot at index' cockroach.log | cut -c 1-13 | uniq -c
   1 I181015 22:06
   1 I181015 22:08
   1 I181015 22:21
   3 I181015 22:48
   9 I181015 22:49
   7 I181015 22:50
   1 I181015 22:51
   3 I181015 22:52
   1 I181015 22:53
   1 I181015 22:54
   2 I181015 22:58
   7 I181015 22:59
   7 I181015 23:00
   5 I181015 23:01
  19 I181015 23:02
   2 I181015 23:03
  40 I181015 23:04
  59 I181015 23:05
  72 I181015 23:06
  62 I181015 23:07
  50 I181015 23:08
  20 I181015 23:09
```

Now those are lots of snapshots, but many of them are small. Let's restrict to snapshots that are at least 10mb:

```
$ rg --no-line-number 'applying Raft snapshot at index' cockroach.log | rg 'encoded size=\d{5}' | cut -c 1-13 | uniq -c
   3 I181015 23:04
   8 I181015 23:05
   8 I181015 23:06
   8 I181015 23:07
  10 I181015 23:08
   7 I181015 23:09
```

They all come in just as things take a severe turn south. This is worth a ping to #10320 (kv level memory accounting), though that would be the second line of defense. The first question is why the cluster decided that it was OK to not take n3 into account when truncating the Raft logs. for lots of ranges.

We can see from the logs that there are Raft snapshots essentially throughout the test, but this is unexpected. Raft snapshots are a recovery mechanism that shouldn't usually be triggered during normal cluster operations.

**Comment by tschottdorf** [comment]
16 of these big snapshots arrive to an initialized replica (i.e. one knowing its bounds). The other 28 hit one that doesn't know its bounds. This ratio is approximately the same when you include all snapshots (105 vs 268), so it's just that we saw more and bigger Raft snapshots, not different ones.

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/blob/a0b7cd4ebddf5ebc8f8c2119b119e57688f072f9/pkg/storage/raft_log_queue.go#L110-L116 

suggests that we'll fall back to Raft snapshots when the estimated raft log size is larger than the replica and I suspect that this is a little noisy/aggressive for small replicas. But especially for this situation there's another catch, namely that the target size is additionally clamped to 4mb (which is going to kick in in the vast majority of cases):

https://github.com/cockroachdb/cockroach/blob/a0b7cd4ebddf5ebc8f8c2119b119e57688f072f9/pkg/storage/raft_log_queue.go#L122

My reading of this is that once you have a few SSTs in your replica, you're going to aggressively commit to the quorum commit index, which is basically saying that it's leaving a lagging replica behind.

I assume that due to the geo-distributed nature of this cluster, n3 is prone to being that odd one out and even more so once it gets to apply all of these snapshots, which come with a large memory amplification, perhaps exacerbated by the sideloading of the SSTs.

**Comment by petermattis** [comment]
Yes, the Raft log is limited to 4MB max size, but proposal quota is supposed to avoid ever hitting that limit. And even if we do hit the truncation limit and allow a replica to fall behind and require a Raft snapshot, the Raft snapshots are serialized by the Raft snapshot queue so there should be a limited number outbound, and in-bound snapshots are also serialized. I'm confused about where the excess memory usage is coming from.

> My reading of this is that once you have a few SSTs in your replica, you're going to aggressively truncate to the quorum commit index, which is basically saying that it's leaving a lagging replica behind.

This is interesting. We limit the size of the Raft log because when the Raft log gets large applying the entries can be slower than sending a snapshot. But that heuristic breaks when the Raft log gets side-loaded sstables.

**Comment by tschottdorf** [comment]
I haven't dared look more, but this is definitely not what we want to see while running this test:

```
root@localhost:26257/defaultdb> select * from crdb_internal.gossip_alerts;
  node_id | store_id | category |            description             | value
+---------+----------+----------+------------------------------------+-------+
        5 |        5 | metrics  | queue.raftsnapshot.process.failure |    10
        3 |        3 | metrics  | queue.raftsnapshot.process.failure |    38
        2 |        2 | metrics  | queue.raftsnapshot.process.failure |     2
        6 |        6 | metrics  | queue.raftsnapshot.process.failure |    14
(4 rows)

Time: 873.526µs
```

**Comment by tschottdorf** [comment]
Seeing long-lived stretches of

```
E181017 09:54:03.321069 399050 storage/queue.go:791  [n2,raftsnapshot,s2,r20548/2:/Table/57/1/3565/{1/-1…-5/-2…}] snapshot failed: (n4,s4):1: remote couldn't accept Raft snapshot 8299c9a5 at applied index 22 with error: [n4,s4],r20548: cannot apply snapshot: snapshot intersects existing range [n4,s4,r20328/1:/Table/5{7/1/3542…-8/1/0/1/…}]
E181017 09:54:03.322758 398811 storage/queue.go:791  [n2,raftsnapshot,s2,r21421/2:/Table/57/1/3656/8/-476/11…] snapshot failed: (n4,s4):1: remote couldn't accept Raft snapshot cd7551ad at applied index 15 with error: [n4,s4],r21421: cannot apply snapshot: snapshot intersects existing range [n4,s4,r20328/1:/Table/5{7/1/3542…-8/1/0/1/…}]
E181017 09:54:03.324610 399052 storage/queue.go:791  [n2,raftsnapshot,s2,r24034/2:/Table/57/1/4754/1/-14{5…-4…}] snapshot failed: (n4,s4):1: remote couldn't accept Raft snapshot 32526b2c at applied index 34 with error: [n4,s4],r24034: cannot apply snapshot: snapshot intersects existing range [n4,s4,r20328/1:/Table/5{7/1/3542…-8/1/0/1/…}]
E181017 09:54:03.326988 398863 storage/queue.go:791  [n2,raftsnapshot,s2,r22671/2:/Table/57/1/3612/2/-676/5…] snapshot failed: (n4,s4):1: remote couldn't accept Raft snapshot c4a4a879 at applied index 15 with error: [n4,s4],r22671: cannot apply snapshot: snapshot intersects existing range [n4,s4,r20328/1:/Table/5{7/1/3542…-8/1/0/1/…}]
```

I wonder if this is related to #31330.

@benesch as an aside, this looks like a merge, but why is the event type "unknown"?

![image](https://user-images.githubusercontent.com/5076964/47079573-23f9a480-d206-11e8-8e2f-93b69bfa1659.png)

This range generally seems to be hanging around alone, which I think means it must've been merged away (I'm running master at 6773854 which has the merge queue on).

![image](https://user-images.githubusercontent.com/5076964/47079573-23f9a480-d206-11e8-8e2f-93b69bfa1659.png)

**Comment by tschottdorf** [comment]
The error is logged at such high rate that all interesting history has been rotated away from the log files.

**Comment by tschottdorf** [comment]
I tried running this thing through the replica GC queue manually, but it's not possible:

![image](https://user-images.githubusercontent.com/5076964/47079880-cdd93100-d206-11e8-8a60-cd817069d392.png)

**Comment by tschottdorf** [comment]
Ah, the "does not have the range lease" method is from the admin endpoint. Looks like it's too big a restriction in this case. cc @a-robinson.
But I think this is also a problem in general. If the gc queue is asking to hold the lease, how are lone survivors going to GC themselves? Nobody else is going to do it for them.

I'm going to patch my binary and restart that node. The problem isn't gonna go away.

**Comment by tschottdorf** [comment]
A, silly me. I was using the `gc` queue but wanted `replicagc`. Ok, this is looking better:

```

Timestamp | Message
-- | --
2018-10-17 10:37:25 | [n4] running replicaGC.shouldQueue
2018-10-17 10:37:25 | [n4] shouldQueue=true, priority=1.000000
2018-10-17 10:37:25 | [n4] running replicaGC.process
2018-10-17 10:37:25 | [n4] querying next range at /Meta2/Table/57/1/3542/4/-1414/6/0/NULL
2018-10-17 10:37:25 | [n4] looked up range descriptor
2018-10-17 10:37:25 | [n4] r1: sending batch 1 Scan to (n4,s4):3
2018-10-17 10:37:25 | [n4] sending request to local client
2018-10-17 10:37:25 | [n4,range-lookup=/Meta2/Table/57/1/3542/4/-1414/6/0/NULL] querying next range at /Meta1/Table/57/1/3542/4/-1414/6/0/NULL/NULL
2018-10-17 10:37:25 | [n4,range-lookup=/Meta2/Table/57/1/3542/4/-1414/6/0/NULL] looked up range descriptor
2018-10-17 10:37:25 | [n4,range-lookup=/Meta2/Table/57/1/3542/4/-1414/6/0/NULL] r1: sending batch 1 Scan to (n4,s4):3
2018-10-17 10:37:25 | [n4,range-lookup=/Meta2/Table/57/1/3542/4/-1414/6/0/NULL] sending request to local client
2018-10-17 10:37:25 | [n4] 1 Scan
2018-10-17 10:37:25 | [n4,s4] executing 1 requests
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] read-only path
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] command queue
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] operation accepts inconsistent results
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] waiting for read lock
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] read completed
2018-10-17 10:37:25 | [n4] 1 Scan
2018-10-17 10:37:25 | [n4,s4] executing 1 requests
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] read-only path
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] command queue
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] waiting for read lock
2018-10-17 10:37:25 | [n4,s4,r1/3:/{Min-System/}] read completed
```

It doesn't seem to go ahead an GC itself, though.

Ah, it should be hitting this case:

```go
	} else if currentMember {
		// This store is a current member of a different range that overlaps with
		// this one. This situation can only happen when we are a current member
		// of the range that subsumed this one, but our replica of the subsuming
		// range has not yet applied the merge trigger. This replica must be
		// preserved so it can be subsumed.
		log.VEventf(ctx, 1, "range merged away; allowing merge trigger on LHS to subsume it")

```

so off I go looking why that doesn't happen.

**Comment by tschottdorf** [comment]
Oh boy, the replica of the subsuming range looks pretty bad:

![image](https://user-images.githubusercontent.com/5076964/47081226-4db4ca80-d20a-11e8-85bb-544d9df4c205.png)

I kinda guessed it, but here we go:

```
I181017 10:45:00.662830 2802359 storage/raft_snapshot_queue.go:94  [n2,raftsnapshot,s2,r20297/2:/Table/57/1/3542/{4/-1…-7/-1…}] sending raft snapshot
I181017 10:45:00.665075 2802359 vendor/go.etcd.io/etcd/raft/raft.go:1096  [n2,s2,r20297/2:/Table/57/1/3542/{4/-1…-7/-1…}] 2 snapshot failed, resumed sending replication messages to 1 [next = 1, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I181017 10:45:00.665100 2802359 storage/queue.go:667  [n2,raftsnapshot,s2,r20297/2:/Table/57/1/3542/{4/-1…-7/-1…}] done 2.293593ms
E181017 10:45:00.665110 2802359 storage/queue.go:791  [n2,raftsnapshot,s2,r20297/2:/Table/57/1/3542/{4/-1…-7/-1…}] snapshot failed: (n4,s4):1: remote couldn't accept Raft snapshot be52a27f at applied index 23 with error: [n4,s4],r20297: cannot apply snapshot: snapshot intersects existing range [n4,s4,r20328/1:/Table/5{7/1/3542…-8/1/0/1/…}]
```

So basically Q=n4/r20328 is waiting for P=n4/r20297 to subsume it, but P is completely busted because it needs a snapshot which can't apply because it intersects Q.

I thought we handled this case. Ah. I think the key is that all of this handling only happens for initialized replicas:

https://github.com/cockroachdb/cockroach/blob/2cbfb514fed209e9e4192bd07af6baa8dd073bab/pkg/storage/store_snapshot.go#L398

According to the screenshot P is not initialized (has an empty EndKey).

**Comment by tschottdorf** [comment]
I guess I don't see how this is impossible:

P upreplicates to n4 but the preemptive snapshot fails and we truncate the logs (see issue above) and before there's a Raft snapshot we do this merge thing which is applied by everyone except P.

**Comment by tschottdorf** [comment]
@benesch since this appears to be merge related, can I kick this over to you? I want to concentrate on how it fails if we don't throw merges in the mix.

**Comment by tschottdorf** [comment]
cluster is here: http://35.237.147.80:26258/debug/logspy?count=1000&duration=10s&grep=r20297

**Comment by benesch** [comment]
Welp, fixing this turns out to involve removing about four lines of code. I'm feeling like this might no longer be a showstopper. I'll describe the issue in the PR that I'm about to submit.

**Comment by benesch** [comment]
Fixed in #31570.

**Comment by awoods187** [comment]
@benesch i thought you just fixed a case of this not working with range merging on that @tschottdorf found. When I created this issue I wasn't using master and therefore range merging wasn't on so shouldn't this issue still be open?

**Comment by tschottdorf** [comment]
I'm kicking off a run that has release-2.1 + https://github.com/cockroachdb/cockroach/pull/31619 (which likely also plays a role here).

**Comment by tschottdorf** [comment]
Uh oh, that didn't go smoothly:

```
181023 09:12:05.696255 350 storage/replica.go:5752  [n5,s5,r9814/2:/Table/60/1/208/{6357…-71210}] RHS of merge r9814:/Table/60/1/208/{63575/0-71210/0} [(n1,s1):1, (n5,s5):2, (n7,s7):3, next=4, gen=2] <- r9818:/Table/60/1/208/71210{-/0} [(n1,s1):1, (n5,s5):2, (n7,s7):3, next=4, gen=1] not present on store; found r9818:{-} [<no replicas>, next=0, gen=0] in place of the RHS
```

**Comment by tschottdorf** [comment]
@benesch full logs attached for your viewing pleasure. I'm going to continue testing without merges again. We should also flip the default back to off on release-2.1.

File (node that it's node `:10` but nodeID 5)

[tpccbench-nodes-12-cpu-16-partition-10-died.zip](https://github.com/cockroachdb/cockroach/files/2505414/tpccbench-nodes-12-cpu-16-partition-10-died.zip)

**Comment by tschottdorf** [comment]
and the `workload` binary also needs to use this PR: https://github.com/cockroachdb/cockroach/pull/31651

or the first partition of the cluster usually ends up being a hotspot (which can exacerbate stability issues but at the very least gives you a zero chance of good perf numbers).

**Comment by tschottdorf** [comment]
I'm running a side-by-side comparison of release-2.1 vs master right now, with the 12 nodes flavor of the test.

With merges turned off, this doesn't look so bad right now (still in the loading phase). I'm watching the `crdb_internal.gossip_alerts` table on both tests and the only alerts I see are replicate queue failures (which is "expected"). During the failing runs that had the merge queue on, I'd quickly see the raft snapshot queue fail thousands of times over each reporting interval.

I thought for a while that release-2.1 had more replicate queue failures, but now that I'm looking again it's the other way around, so I think this is just happenstance.

Going to see if these runs make it to the line searching phase and if they do, whether they produce reasonable results.

**Comment by tschottdorf** [comment]
The master one had a node die with OOM:

> I181023 12:23:27.138690 375 server/status/runtime.go:465  [n10] runtime stats: 13 GiB RSS, 470 goroutines, 8.3 GiB/37 MiB/8.7 GiB GO alloc/idle/total, 3.7 GiB/4.3 GiB CGO alloc/total, 22292.1 CGO/sec, 37.9/29.2 %(u/s)time, 0.1 %gc (1x), 210 MiB/6.5 MiB (r/w)net

The culprit, as we had seen before, is

![image](https://user-images.githubusercontent.com/5076964/47360591-2d848000-d6d0-11e8-996f-257db2d3c12d.png)

Go Allocated memory grew steadily starting around 12:15pm:

![image](https://user-images.githubusercontent.com/5076964/47360755-8fdd8080-d6d0-11e8-8abd-84b4ae8773c9.png)

**Comment by tschottdorf** [comment]
This does seem to be related to a high number of snapshots coming in:

```
$ rg --no-filename --no-heading --no-line-number 'applying Raft snapshot at index' *.log | cut -c 1-13 | sort | uniq -c
 424 I181023 10:16
   4 I181023 10:17
   2 I181023 10:20
   1 I181023 10:22
   1 I181023 10:24
   2 I181023 10:26
   2 I181023 10:27
   1 I181023 10:28
   1 I181023 10:29
   1 I181023 10:30
   1 I181023 10:33
   2 I181023 10:34
   1 I181023 10:36
  37 I181023 10:37
  64 I181023 10:38
  34 I181023 10:39
  37 I181023 10:40
  28 I181023 10:41
  33 I181023 10:42
  38 I181023 10:43
  24 I181023 10:44
  27 I181023 10:45
  28 I181023 10:46
  21 I181023 10:47
  34 I181023 10:48
  27 I181023 10:49
  28 I181023 10:50
  29 I181023 10:51
  27 I181023 10:52
  33 I181023 10:53
  31 I181023 10:54
  28 I181023 10:55
  31 I181023 10:56
  38 I181023 10:57
  20 I181023 10:58
   4 I181023 11:01
   4 I181023 11:02
   2 I181023 11:51
   4 I181023 12:02
   2 I181023 12:09
  56 I181023 12:14
  74 I181023 12:15
  92 I181023 12:16
  84 I181023 12:17
 100 I181023 12:18
 106 I181023 12:19
 134 I181023 12:20
  82 I181023 12:21
 118 I181023 12:22
  42 I181023 12:23
```

**Comment by tschottdorf** [comment]
In accordance with the Raft snapshots, the replica also gets more ranges (not surprising)

![image](https://user-images.githubusercontent.com/5076964/47361345-f3b47900-d6d1-11e8-8aa1-c6f13f7ac416.png)

The main anomaly here is that the snapshots are coming in via Raft and not the preemptive path. We talked earlier about how this might come to be for large snapshots. But the vast majority I'm seeing here are pretty small (between 100 and 999 bytes):

```
$ rg --no-line-number --no-heading --no-filename 'applying Raft snapshot at index' *.log | rg 'encoded size=\d{3}[^\d]' | cut -c 1-13 | sort | uniq -c
  49 I181023 10:16
   1 I181023 10:17
   3 I181023 10:37
  12 I181023 10:38
   1 I181023 10:39
   1 I181023 10:40
   1 I181023 10:41
   3 I181023 10:42
   4 I181023 10:43
   1 I181023 10:47
   1 I181023 10:48
   1 I181023 10:55
   2 I181023 10:56
   2 I181023 10:57
   1 I181023 10:58
   2 I181023 11:01
   4 I181023 11:02
   2 I181023 11:51
   4 I181023 12:02
   2 I181023 12:09
  56 I181023 12:14
  70 I181023 12:15
  76 I181023 12:16
  78 I181023 12:17
  96 I181023 12:18
 104 I181023 12:19
  46 I181023 12:20
   8 I181023 12:21
   8 I181023 12:23
```

**Comment by tschottdorf** [comment]
Something that confused me is that the "ranges" metric is pretty much at zero but I think this is probably due to how the metric counts (does it use the replica with the smallest replicaID as a counter?)

The range count definitely moved up gradually (see the leaseholders line).

But what I'm seeing is that around 12:15 the split queue really started to go at it:

![image](https://user-images.githubusercontent.com/5076964/47361869-53f7ea80-d6d3-11e8-8e97-f9051a74fc0d.png)

Perhaps this is somehow related; splits can certainly propose large Raft commands. However, it does seem that the raft snapshot activity begins a minute or two before the splits.

**Comment by tschottdorf** [comment]
Well, after having chatted with @nvanbenschoten about the profile, there is little doubt that we're running out of memory due to a large amount of Raft proposals that we hold in memory. These proposals for the most part are large (since we see that mostly 33mb chunks are allocated for them), so they're very likely AddSSTable commands. (For sanity, I checked inuse_objects and the picture there is much less concentrated as you'd expect).

alloc_space shows around 15% unmarshaling `ReplicatedEvalResult_AddSSTable` which supports this as well (I'm not sure when the baseline is "reset" here so that it's likely 15% across the whole test run, i.e. including the time before problems started - right @nvanbenschoten?). `alloc_objects` doesn't show anything relevant to this issue (again, expected - we're dealing with few large things and not many things).

So a possible sequence of events is

1. node picks up a bunch of new ranges, but via raft snapshots
1. raft logs get applied and happen to contain loads of AddSSTable commands
1. boom

where I'm not sure about the first part.

**Comment by tschottdorf** [comment]
On the positive-ish side, the import on 2.1 actually went through, but then the test immediately barfed via

> --- FAIL: tpccbench/nodes=12/cpu=16/partition (10324.73s)
	test.go:639,cluster.go:1453,tpcc.go:689,tpcc.go:343: failed with output "Error: dial tcp 10.142.0.67:26257: socket: too many open files\nError:  exit status 1\n": /Users/tschottdorf/go/bin/roachprod run tobias-tpccbench12-v21:13 -- ./workload run tpcc --warehouses=10000 --split --scatter --ramp=5m0s --duration=1ms --tolerate-errors --partitions=4 {pgurl:1-12}: exit status 1

ssh'ing in the machine, I see 

> open files                      (-n) 65536

which is the same for root.

**Comment by tschottdorf** [comment]
works after restarting, at least for now. Curious what you think about this though, @nvanbenschoten.

**Comment by tschottdorf** [comment]
Not really a reason to celebrate, but at least this isn't a regression - From @awoods187' crash on 2.0.6:

![image](https://user-images.githubusercontent.com/5076964/47367995-1bf7a400-d6e1-11e8-98df-0a344840f4ef.png)

Pretty sure we're going to find that the remaining symptoms line up. There aren't any profiles (2.0.6 doesn't have that feature).

Yep, here we go: (mem blowup is from ~13:57 onwards)

```
$ rg --no-filename --no-heading --no-line-number 'applying Raft snapshot at index' cockroach.andy*.log | cut -c 1-13 | sort | uniq -c
  11 I181023 13:08
   8 I181023 13:09
   4 I181023 13:14
   6 I181023 13:15
   6 I181023 13:16
  11 I181023 13:17
   2 I181023 13:18
   1 I181023 13:26
   1 I181023 13:28
   1 I181023 13:29
   2 I181023 13:30
   1 I181023 13:36
   2 I181023 13:38
   2 I181023 13:39
   1 I181023 13:40
   2 I181023 13:43
   1 I181023 13:45
   1 I181023 13:55
  19 I181023 13:57
  38 I181023 13:58
  30 I181023 13:59
  41 I181023 14:00
  38 I181023 14:01
   9 I181023 14:02
  11 I181023 14:04
```

**Comment by tschottdorf** [comment]
on 2.1, in the meantime I got

```
--- FAIL: tpccbench/nodes=12/cpu=16/partition (889.58s)
	test.go:639,cluster.go:1453,tpcc.go:689,tpcc.go:343: error running tpcc load generator:

		Error: preparing
				UPDATE district
				SET d_next_o_id = d_next_o_id + 1
				WHERE d_w_id = $1 AND d_id = $2
				RETURNING d_tax, d_next_o_id: read tcp 10.142.0.68:52646->10.142.0.64:26257: read: connection reset by peer
		Error:  exit status 1

		: /Users/tschottdorf/go/bin/roachprod run tobias-tpccbench12-v21:13 -- ./workload run tpcc --warehouses=10000 --active-warehouses=6000 --tolerate-errors --ramp=5m0s --duration=10m0s --partitions=4 --split {pgurl:1-12}: exit status 1
FAIL
```

The cluster is "green" (I would've expected a node to have crashed, but apparently not). I'm not seeing anything obvious from the logs.

**Comment by tschottdorf** [comment]
To circle back to the raft log truncation discussion above in https://github.com/cockroachdb/cockroach/issues/31409#issuecomment-430193363 (and the related comment https://github.com/cockroachdb/cockroach/issues/31732#issuecomment-432666745) I took a good look at the raft log size tracking.

There's one obvious problem: when we increment `raftLogSize`, we include sideloading (i.e. we count the sideloaded bytes). However, when we truncate, we only reduce by the `SysBytes` corresponding to removing the "thin" entries.

As a result, when replicas are hit with a stream of AddSSTables, they'll start truncating the log extremely aggressively.

Well, that should be easy to fix. I'll do so and run another round of experiments.

**Comment by petermattis** [comment]
> There's one obvious problem: when we increment raftLogSize, we include sideloading (i.e. we count the sideloaded bytes). However, when we truncate, we only reduce by the SysBytes corresponding to removing the "thin" entries.

Yeah, that would be a problem.

**Comment by nvanbenschoten** [comment]
> I wasn't aware that we also refuse preemptive snapshots based on the Raft log size. But something seems to be off if we're seeing this error regularly.

Avoiding snapshots and waiting on any operation that requires quorum seems like a recipe for disaster. We already saw this bite us when we blocked snapshots on large range sizes which in turn depended on splits. I guess we also block them on log truncation. Maybe we can wait a little bit in these scenarios to allow a log truncation if it's ever going to happen, but I don't see how we can rely on it happening, so eventually we need to send the snapshot. Snapshots are a recovery mechanism so we need to be careful preventing them indefinitely.

**Comment by tschottdorf** [comment]
Agreed.

In the meantime, this transpired:

```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '104.196.114.242' (ECDSA) to the list of known hosts.
node_id store_id        category        description     value
4       4       metrics queue.raftsnapshot.process.failure      919
7       7       metrics queue.raftsnapshot.process.failure      1350
5       5       metrics queue.raftsnapshot.process.failure      160
3       3       metrics queue.replicagc.process.failure 1
8       8       metrics queue.raftsnapshot.process.failure      10
```

**Comment by tschottdorf** [comment]
And, on a run of import/tpch/nodes=8:

```
Every 2.0s: echo 'select * from crdb_internal.gossip_alerts;' | roachprod sql tobias-1540921719-import-tpch-nodes-8:1                                                                                                             toblerone.fritz.box: Tue Oct 30 21:45:43 2018

Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '35.231.45.225' (ECDSA) to the list of known hosts.
node_id store_id        category        description     value
8       8       metrics queue.raftsnapshot.process.failure      116
3       3       metrics requests.slow.raft      1
1       1       metrics requests.slow.raft      2
```

🔥

**Comment by tschottdorf** [comment]
on 11node:

```
E181030 20:47:08.096492 729188 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot ebed16e6 at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
E181030 20:47:09.096722 729152 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 53407301 at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
E181030 20:47:10.097538 729162 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot b63df09b at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
E181030 20:47:11.097173 729811 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 5c3cce28 at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
E181030 20:47:12.097500 730186 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot cd01c1a2 at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
E181030 20:47:13.096143 730628 storage/queue.go:831  [n8,raftsnapshot,s8,r56244/5:/Table/55/1/61{10-20}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot bd422462 at applied index 29 with error: [n3,s3],r56244: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r56065/2:/Table/55/1/6{100-220}]
```

**Comment by tschottdorf** [comment]
Status for r56065:

![image](https://user-images.githubusercontent.com/5076964/47749522-900bec00-dc8d-11e8-8a4e-7bfb5691d839.png)

**Comment by tschottdorf** [comment]
This is odd. n3 doesn't seem to require a snapshot (truncated index is 10, same as the applied index, so it should be good though it has an "empty log" which maybe makes this some broken edge case?).

Yet, on n3 there's nothing. I'd expect to see MsgApp from the leader, but we're only getting heartbeats.

```
181030 20:55:13.440343 179611402 server/debug/logspy.go:182  intercepting logs with options {Count:1000 Duration:30s Grep:r56065}
I181030 20:55:13.494595 206 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:13.695658 184 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:13.855559 332 storage/store.go:3349  [n3,s3,r56065/2:/Table/55/1/6{100-220}] incoming raft message:
3->2 MsgHeartbeat Term:6 Log:0/0
I181030 20:55:13.855604 332 storage/raft.go:141  [n3,s3,r56065/2:/Table/55/1/6{100-220}] raft ready (must-sync=false)
  Outgoing Message[0]: 2->3 MsgHeartbeatResp Term:6 Log:0/0
I181030 20:55:13.855626 332 storage/replica.go:5066  [n3,s3,r56065/2:/Table/55/1/6{100-220}] coalescing beat: {RangeID:56065 FromReplicaID:2 ToReplicaID:3 Term:6 Commit:0 Quiesce:false}
I181030 20:55:13.895401 219 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:14.094888 311 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:14.299117 216 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:14.495196 219 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:14.695294 370 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:14.854299 294 storage/store.go:3349  [n3,s3,r56065/2:/Table/55/1/6{100-220}] incoming raft message:
3->2 MsgHeartbeat Term:6 Log:0/0
I181030 20:55:14.854317 294 storage/raft.go:141  [n3,s3,r56065/2:/Table/55/1/6{100-220}] raft ready (must-sync=false)
  Outgoing Message[0]: 2->3 MsgHeartbeatResp Term:6 Log:0/0
I181030 20:55:14.854334 294 storage/replica.go:5066  [n3,s3,r56065/2:/Table/55/1/6{100-220}] coalescing beat: {RangeID:56065 FromReplicaID:2 ToReplicaID:3 Term:6 Commit:0 Quiesce:false}
I181030 20:55:14.895664 238 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:15.095386 402 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:15.294764 333 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:15.495236 299 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:15.695444 381 storage/replica.go:4741  [n3,s3,r56065/2:/Table/55/1/6{100-220}] not quiescing: not leader
I181030 20:55:15.853421 432 storage/store.go:3349  [n3,s3,r56065/2:/Table/55/1/6{100-220}] incoming raft message:
3->2 MsgHeartbeat Term:6 Log:0/0
```

On the leader, we see that it's heartbeating n3 (replicaID=2), but it's not including a Commit index.

```
I181030 20:57:05.759049 254 storage/raft.go:141  [n4,s4,r56065/3:/Table/55/1/61{00-10}] raft ready (must-sync=false)
  Outgoing Message[0]: 3->1 MsgHeartbeat Term:6 Log:0/0 Commit:24
  Outgoing Message[1]: 3->2 MsgHeartbeat Term:6 Log:0/0
```

This must indicate something. Perhaps Raft is indeed trying to send a snapshot but we're running into Raft snapshot queue starvation (again): https://github.com/cockroachdb/cockroach/issues/31947#issuecomment-434383267.

**Comment by tschottdorf** [comment]
Yeah, I'm inclined to believe that this is some edge case and that Raft is trying to send a snapshot. I'm basing this off of

https://github.com/cockroachdb/vendored/blob/50f622b97b353426537455f5be003d15234d23f0/go.etcd.io/etcd/raft/raft.go#L532-L549

which indicates that we should see a nonzero commit index whenever Raft knows anything about the peer's progress.

**Comment by tschottdorf** [comment]
Another thing worth pointing out is that oddly, the range above has its leaseholdership still at n3 (leader is n4).

I went to n7 and grabbed ~20s worth of declined snapshots to get the rangeIDs which have the problem: 

```
$ cat delme | grep "couldn't accept" | grep -oE 'n3,s3,r[0-9]+/' | cut -c 8- | grep -Eo '[0-9]+' | sort | uniq -c
   7 56058
  14 56065
   7 56077
  56 56079
   7 56082
  14 56083
  91 56216
  42 56225
  21 56230
  28 56262
  61 56303
 515 56311
   7 56318
  46 56375
```

I checked all of them and they look exactly like the screenshot above. But looking for snapshot errors on n4, I found this one which has the exact same problem but doesn't have this lease-leader discrepancy (so that I assume that it's not essential to the bug):

![image](https://user-images.githubusercontent.com/5076964/47752478-d7e24180-dc94-11e8-8943-fdbc131dfe7e.png)

The lease mismatch deserves investigation in itself too, though. How do we end up in a state where n3 needs a snapshot but it has the lease? I could be convinced that there's a rare race where a leadership transfer happens to a target that is also about to be "truncated away". But we're seeing dozens of ranges here that have this, and mostly adjacent ones.

**Comment by tschottdorf** [comment]
Praise be to @a-robinson: I am able to heal individual ranges by sending them manually through the Raft snapshot queue:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/5076964/47752925-34922c00-dc96-11e8-97eb-8f34fc870083.png">

The range is now healthy.

**Comment by tschottdorf** [comment]
My main take-away from this is that https://github.com/cockroachdb/cockroach/issues/31947#issuecomment-434383267 is actually the major problem here that magnifies some other minor problems.

I'm going to send a fix tomorrow and also run this experiment a few more times with it. When #31875 is in I'll start enforcing zero Raft snapshots (queued or sent) on all tests that shouldn't have any, so we're going to get a pretty good understanding of the fact that these ranges needed one.

The leaseholder mismatch is still a mystery to me. By running the range through the queue (on n4, see the screenshot above) the lease actually moved to n7. I have no idea why. Might've been a lease balancing thing.

**Comment by tschottdorf** [comment]
I'm running another instance of tpccbench/nodes=11/cpu=32 (with a fix for the Raft log queue starvation) and am seeing an underreplicated range stick around again, very early in the test (like https://github.com/cockroachdb/cockroach/issues/31409#issuecomment-434417300). This time, there's no preemptive snapshot that was refused based on log size, though the Raft log is too large. This is probably something that can happen during SCATTER, though I would expect to see a failed upreplication somewhere, which I don't (at least not when I grep for the RangeID on all nodes). We're probably relying on the replicate queue to pick this range up. I ran it through the queue manually (letting it decide whether to even queue it) and yup, the problem got fixed. We had ~10k ranges at that point. The scan interval is 10 minutes and the leading node had at most 4k ranges worth of leaders at that point, and its replicate queue was pretty much idle, though there's a steady stream of lease transfers. The scanner interval is 10 minutes, but I observed the phenomenon for at least 13 minutes before I queued it manually. Not sure what's going on there but I'll logspy the next time I see it.

**Comment by spencerkimball** [comment]
@tschottdorf, on my list of todos for dealing with nodes that contain many ranges is a better mechanism for enqueueing ranges for up-replication than the current replica scanner / purgatory mechanism. Because we now have a min idle time (which honestly is still too aggressive IMO), if you have 60,000+, you start taking longer than 10m to examine ranges. The purgatory is very aggressive about serially reprocessing with zero min idle time. The current state of things is less than ideal.

Instead of waiting on the scanner, I wanted to have “now live” changes to node liveness result in a scan over in-memory range descriptors to enqueue ranges which need up replication And can accept a store on the newly live node as a target.

Would this help for this case, or would the node liveness not change in such a way that this proposed mechanism would trigger?

**Comment by tschottdorf** [comment]
I'm not aware of any node liveness changes in these tests. Seems difficult to "reactively" pick the range up in this scenario (after a "manual intervention" such as scatter left it in a downreplicated state without enqueuing it again). This is probably mainly a bug in scatter, though.

**Comment by tbg** [comment]
@petermattis could you take a look at the history of this flakiness to see if you can shake out what made this so much worse? Replication-related changes are the most likely culprit (absent any changes in the import/restore use of scatter). I also suspect that our introduction of time limits on some of the nightly tests exposed some of the failures that would otherwise have gone unnoticed. Unfortunately, the TC test history only reaches back one month, so we'll only be able to see from it whether we introduced a new problem within that timeframe.

Next, to see the problem in action, it should be enough to run `restore2TB` or `import/tpch/nodes=4`. The latter has the advantage that it's a smaller cluster, but you have to sit out the `import` phase (which takes a long time).
As the replica count goes up, watch the Raft Snapshot Queue page (or set up a `watch` on `crdb_internal.node_metrics` that filters on the corresponding pending gauge. It's worth looking at individual nodes as the contribution is usually localized (since it's due to splitting). If the problem doesn't materialize within the first ~30min, it may not happen.

There's also always a good chance that @awoods187 has a cluster that's already in a bad state at any given point in time.

Using `logspy` with a grep for `raftsnapshot,` is the best way that I've found to see what's going on inside of the queue. It'll give you an idea of the throughput and the kind of snapshots its sending when invoked with a long enough duration, and it also has the rejections. If you see unexplainable stalls, they're likely caused by the [Raft snapshot semaphore](https://github.com/cockroachdb/cockroach/blob/25922fcc3313f586fb1c868f1d6f95fadff4bcbc/pkg/storage/store_snapshot.go#L342-L383).

I think I understand pretty well how the first of these snapshots comes to be. What I've looked at less is how that sporadic snapshot-requiring Replica gets multiplied by splits and whether a small tweak to AdminSplit (to delay or refuse splits that have a follower requiring a snapshot) can already defuse the situation. Or whether there's something specific about the split-scatter code in backup/restore (which is not identical, btw) that exacerbates this issue.

I'm going to spend a little more time investigating whether I accidentally made things worse in https://github.com/cockroachdb/cockroach/pull/31875: it works perfectly for three node clusters, but when there's a lot of replica movement the case in which we're artificially delaying the snapshot might be hit more frequently. I think I can move the decision to drop the message to the recipient, which is a full replica and can make an informed decision about whether it's the "rare case" or the sender waiting for the split trigger. The reason I suspect there's an issue here is because I expanded the test from that PR to four nodes and added scattering before and after each split. I see snapshots only occasionally (and for fixable but well-understood reasons), but they are always artificially delayed by the mechanism added in the PR.

**Comment by tbg** [comment]
I've had good results with #32533 for backup2TB, even when merges are on:

![image](https://user-images.githubusercontent.com/5076964/48851454-65ecac00-edab-11e8-9157-45717658c9d0.png)

![image](https://user-images.githubusercontent.com/5076964/48851501-861c6b00-edab-11e8-9c24-5c7fb2969b1c.png)

To be fair, this also didn't look too bad in a previous run without that fix, but I did see a large spike in Raft snapshots (hundreds) at the beginning that went down. I think I might've gotten lucky there, and that this spike can in principle grow over time.

The main problem with merges appears to be that it adds more rebalancing into the mix (this could also be the case for IMPORT, which uses a different split-scatter strategy). Rebalancing leads to Raft snapshots in some buggy edge cases (GC'ing preemptive replicas prematurely, for example, but there's also a tricky one around rapid up-down-upreplication). #32533 lets these snapshots resolve much faster, which is why I hope that it prevents the issue from spiraling out of control in the first place.

@awoods187 what's your current operation that you'd like to run but weren't able to due to this issue? I'd like to give it another try.

**Comment by petermattis** [comment]
>  could you take a look at the history of this flakiness to see if you can shake out what made this so much worse? 

I didn't see any particular point in time that flakiness jumped for `restore2TB` or the `import/tpch` tests. 

> I've had good results with #32533 for backup2TB, even when merges are on:

Did you mean `restore2TB`?

**Comment by tbg** [comment]
Yes. Edited.

**Comment by awoods187** [comment]
I was hitting this last week trying to import tpc-c 10k on AWS. I know that @ajwerner has hit a few different times on aws on 50k

**Comment by tbg** [comment]
The nightlies post #32594 look very promising (they all passed, and didn't have Raft snapshot buildup).

I'm going to optimistically close this, but @ajwerner and @awoods187 please let me know when imports fail (in the way specific to this issue).
