### ISSUE TITLE
sql,storage: splits may split SQL rows

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#43094]
SQL currently does not tolerate it when the column families of a row span more than one range. This restriction seems superficially reasonable: splitting a column family over a range is not generally desired, and so it makes sense to avoid it; that the SQL layer crashes if it happens seems less due to some deep restriction rather than implicit assumptions. Besides, we do rely on this invariant for some less interesting items such as counting the number of rows in a backup (or something like that, @dt knows the details).

Unfortunately, it is very hard to uphold this invariant since splitting is inherently a KV operation: it operates on an arbitrary `roachpb.RKey` which has no SQL schema information attached to it. SQL keys are not self-describing: one can not look at a key and decide whether it could possibly split a SQL row between two column families. Essentially this means that the caller to `AdminSplit` must promise that the split key is "safe", i.e. that in no possible world is or could there ever be a row whose column families fall on opposite sides of the split. It's hopefully clear that from an architectural point of view, this is already not a good idea, and predictably, it has brought us into a number of pickles, most recently in https://github.com/cockroachdb/cockroach/pull/43078.

It also becomes a real problem since the KV layer issues splits autonomously based on size and load.

For size-based splits, we do an awkward dance which mostly works out because we can orient ourselves around the keys that actually exist in the range, and (basically) make the assumption that they're all SQL row keys. Under this assumption, we can read the column family suffix and determine whether the split is safe.

For load-based splits, it's more complicated. The split point for load-based splits is determined by sampling from the spans of incoming requests. These keys are more often than not real SQL row keys because when SQL scans a full row, it does not construct the full key - it omits the column prefix. Concretely, in `kv`, rows are encoded on disk as `/Table/53/1/<id>/0` but the SQL layer will read them via a scan starting at `/Table/53/1/<id>`.
The latest iteration on this layer cake of hacks calls `EnsureSafeSplitKey` and on errors assumes that the key is not between rows. This should mostly be true, but it's a very subtle invariant that, even if not violated in practice, emits a pungent smell that is hard to ignore. As far as KV is concerned, a client may as well issue a number of scans starting at `/Table/53/1/<id>/0/somebogussuffix` from which you can't decode the column family ID but which squarely splits the row for `id` in half (if it has more than one column family, something not true in KV).

See:

https://github.com/cockroachdb/cockroach/pull/42056 - general trove of information
https://github.com/cockroachdb/cockroach/issues/16344 - old attempt at cleaning this up
https://github.com/cockroachdb/cockroach/pull/42833 - first recent really broken attempt
https://github.com/cockroachdb/cockroach/pull/43078 - second less, but still broken, attempt

Since this area of code is active now, we should figure out how to fix the mess we got ourselves into.

A few options come to mind:

- drop any guarantees that prevent splitting between column families. Rationale: as long as KV is in charge of splitting, it can't guarantee it without subtle and historically repeatedly violated invariants. Better rip off the band aid now.
- put a higher-level system in charge of splitting. That system needs to know about SQL schemas etc and will only ever split at "safe" keys. Rationale: it's the sane way to get the invariant that is currently being assumed.
- keep splitting in KV, but only ever split at existing keys. Rationale: it's a more reasonable assumption that if the SQL layer is using a range for table data, there can't be any "non-table data" interspersed with rows. Con: it's an awkward restriction that is sure to be hard to work with in practice, for example we can't split off empty tables any more.

Curious about other options. Of the ones listed here, in the short term, the first one seems like the only reasonable one.

Someone should also think through interleaved tables and whether they can add a new toxin to the mix. I hope not because (or so I assume) interleaved tables can never "partition" the columns of a parent row (?).

@nvanbenschoten could you bring this issue to the next KV weekly/generally drive it forward?

**Comment by jordanlewis** [comment]
What are the concrete consequences of accidentally splitting rows across ranges? Can we work to prevent those consequences instead?

Given that by definition it'll be rare to have a row split across two ranges, is it really that big of a deal to lift this restriction? From SQL execution's perspective, Ranges are completely abstracted away - we do all of our operations via interfaces that concatenate data from multiple ranges as you'd expect.

I think given how painful this is to fix, we ought to consider going in the other direction and loosening our requirements to *not* have split rows.

**Comment by tbg** [comment]
@jordanlewis what you're suggesting is option 1 and it's my favorite as well. All of the consequences live above KV.

See @dt's [comment](https://github.com/cockroachdb/cockroach/pull/42056#issuecomment-552431973) for bulk i/o and scroll down from there to see the one place we found where SQL makes assumptions (~ kvfetcher considers row to be done when hitting a range boundary)

**Comment by jordanlewis** [comment]
Ah I see. I think we could probably fix this then...

**Comment by lunevalex** [comment]
@tbg @jordanlewis now that we increased the range size to 512MB, do we still want to consider doing this at some point in the future?

**Comment by ajwerner** [comment]
Another proposal that isn't in the list is to propagate information to KV about valid split points within key ranges. As we look towards 21.1 we are looking towards revamping the ways in which KV is informed about zone configs and split points. Today we propagate the entire system config which is not scalable and poorly engineered. Perhaps it wouldn't be so onerous for the system config (or something around it) to indicate a boolean function of a key to determine whether it forms a valid split point.

**Comment by tbg** [comment]
Yes, there's still a problem here. It's just that the duct tape is working at the moment.

**Comment by tbg** [comment]
We now hit this in production: https://github.com/cockroachlabs/support/issues/2302

**Comment by michae2** [comment]
Can we close this, given that https://github.com/cockroachdb/cockroach/issues/103483 was fixed?

**Comment by dt** [comment]
I think this is still relevant / open.

We've seen a new manifestation of this bug in almost every release I can remember, either in restore, load-based-splits, schema changes, etc, since the underlying issue -- that a kv split _can_ be created between KVs of a row -- still exists. I'd argue that https://github.com/cockroachdb/cockroach/issues/103483 was closed since we fixed an instance of the bug, but the underlying bug in the design persists and I think this issue is the closest we have to tracking that?

https://github.com/cockroachdb/cockroach/issues/109857 we could probably fold into this.

**Comment by dt** [comment]
I wonder if we should fold https://github.com/cockroachdb/cockroach/issues/112702 into this too.
