### ISSUE TITLE
server: decommissioning self can hang

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#56718]
When a node is marked as decommissioned, it loses access to the cluster. When a node is decommissioned through itself (i.e. when the decommission cli is pointed at the node that is to be decommissioned, a common pattern), it can happen that the cluster learns that the node is decommissioned before the node itself does. In that case, the user will experience the decommissioning command hanging indefinitely. Typically, the server side of the endpoint is hanging in the KV layer, unable to perform KV operations.

I've seen this in #56568 when the very last step allows decommissioning through itself (I am changing that PR now to avoid this bug for now).

When this issue is closed, the last decommission step should read

```go
fullyDecommissionStep(h.getRandNodeOtherThan(pinnedUpgrade), h.getRandNode(),
```

or explicit coverage of this case should be introduced (preferrably).

**Comment by tbg** [comment]
The mechanism that excludes decommissioned nodes from the cluster lives here:

https://github.com/cockroachdb/cockroach/blob/3cda1c7113556f07df9beefb9c016e5c5d7422f0/pkg/server/server.go#L275-L306

In a nutshell, a decommissioned node will receive this error from the `Ping` requests that its `rpc.Context` periodically sends:

https://github.com/cockroachdb/cockroach/blob/3cda1c7113556f07df9beefb9c016e5c5d7422f0/pkg/server/server.go#L285-L288

This is a structured error. Unfortunately, in practice the decommissioning code

https://github.com/cockroachdb/cockroach/blob/e2572753be0efcbd3f17cdd020d70e22e9b21582/pkg/server/admin.go#L1866-L1938

only gets to see the error after it has propagated across the network and percolated up from, usually, the KV API. KV unfortunately wasn't equipped to transport arbitrary structured payloads. However, following this issue originally being filed, this was rectified in https://github.com/cockroachdb/cockroach/pull/56603 so that today we should be able to reliably detect this error with its original structure.

The first step is to verify that. We should extend this test

https://github.com/cockroachdb/cockroach/blob/69bc989b5746ecaf824c2abf5d6955f2dd54affe/pkg/server/connectivity_test.go#L341-L392

and use the decommissioned node's KV API to run a scan that we know has to touch another node, and check that the returned error carries the right structure. I think the best way to do that is to use `ScratchRange()`, relocate that range to one of the other nodes, and scan it thorough the decommissioned node.

Assuming this works, we can either trust that anything that DecommissionStatus will do does indeed preserve structure (definitely we'll want a test of this method either way, and maybe it's clear that it works once we have it?) or we try to add some catch-all monitoring loop at the top of `DecommissionStatus`, very bad prototype here:

```go
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	stopper.RunAsyncTask("watch-decommissioned-self", func(ctx context.Context) {
		defer cancel()
		t := timeutil.NewTimer()
		defer t.Stop()
		const d = time.Second
		t.Reset(d)
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				t.Read = true
				t.Reset(d)
				// Check that we're not decommissioned $somehow
				var decommissioned bool // TODO populate this somehow
				if decommissioned {
					// Make sure that the method returns successfully
					// without an error despite ctx cancellation.
					return
				}
			}
		}

	})

```

A related issue is https://github.com/cockroachdb/cockroach/issues/56208 - there's a middleware that connects our `errors` library with grpc errors. Unfortunately, there's some kind of blocker related to our protobuf version which is unlikely to resolve in the short term. So this probably won't influence the solution here just yet.

**Comment by erikgrinaker** [comment]
@tbg `codes.PermissionDenied` wasn't propagated all the way through the KV layer, which is also what caused the hang (it was interpreted as a retryable error and retried indefinitely). I've fixed most of the issues on a branch, and am working on a final hurdle:

`DistSender.sendPartialBatch()` only returns a `response`, and thus has to wrap the gRPC client error with `roachpb.NewError()` to place it in the returned response:

https://github.com/cockroachdb/cockroach/blob/477f39d09668abcce1b2cd2801ece4643d123171/pkg/kv/kvclient/kvcoord/dist_sender.go#L1533

This is then unwrapped in `DB.sendAndFill()` during scan execution:

https://github.com/cockroachdb/cockroach/blob/daf42d6b8c87cbd3c0cf831b0cd8f7b97fafd3f5/pkg/kv/db.go#L724

The wrapper `roachpb.Error` can retain structured error information in `EncodedError`, either using a registered error encoder or falling back to a Protobuf `Any` field for any Protobuf errors:

https://github.com/cockroachdb/vendored/blob/1b1d687f4f28f4d6aac6ec8645cbc22e28c0b183/github.com/cockroachdb/errors/errbase/encode.go#L68-L71

The root `grpcstatus.Error` is in fact a Protobuf message:

https://github.com/cockroachdb/vendored/blob/1b1d687f4f28f4d6aac6ec8645cbc22e28c0b183/google.golang.org/grpc/internal/status/status.go#L95-L101

but unfortunately this is a vanilla Go Protobuf message not a GoGoProto message, and since the message type therefore isn't registered with the GoGoProto type registry it can't be used in an `Any` field since the decoder doesn't know the type to decode into.

There are a few different ways to go from here. For now, I'll hardcode automatic encoding/decoding of `grpcstatus.Error` in `cockroachdb/errors`, using its [`extgrpc`](https://github.com/cockroachdb/errors/tree/master/extgrpc) package to represent the error as a GoGoProto type (even though this package is just said to be an example, despite it being used in the gRPC middleware you mentioned).

I feel like the ideal solution would be to replace all use of `grpcstatus` in CockroachDB with https://github.com/gogo/status, a cross-compatible package provided by the GoGo project. In that case these errors should "just work" across `roachpb.Error`. Otherwise, we could consider using https://github.com/gogo/googleapis, GoGo-supplied versions of the Google Protobuf APIs, and automatically convert to these in `cockroachdb/errors`. Although I suppose the uncertain future of the GoGo project may mean that we should reduce dependencies on it instead.

Would love to get your thoughts on this, I'll cobble together a temporary hack in the meanwhile.

**Comment by tbg** [comment]
Thanks Erik! I didn't think about the issue regarding the type registries at all. Honestly I'm a bit out of my depth with this; @knz is really the authority here (Raphael, mind chiming in?). Using a wrapper decoder to get things working seems good for now. But it seems that you have also found an issue with `cockroachdb/errors` where it doesn't work as perhaps expected when mixing and matching gogoproto.

**Comment by tbg** [comment]
This is the unit test repro, right?

```go
func TestFoo(t *testing.T) {
	rec := tracingpb.RecordedSpan{
		TraceID: 12,
	}
	var status *grpcstatus.Status
	{
		var err error
		status, err = grpcstatus.New(codes.PermissionDenied, "foo").WithDetails(&rec)
		require.NoError(t, err)
		require.NotNil(t, status)
	}

	ctx := context.Background()
	encErr := errors.EncodeError(ctx, status.Err())
	err := errors.DecodeError(ctx, encErr)
	require.Equal(t, status.Err(), err)
}
```

```
=== RUN   TestFoo
    tracer_test.go:572: 
        	Error Trace:	tracer_test.go:572
        	Error:      	Not equal: 
        	            	expected: *status.Error(&status.Error{Code:7, Message:"foo", Details:[]*anypb.Any{(*anypb.Any)(0xc000112c30)}, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0})
        	            	actual  : *errbase.opaqueLeaf(&errbase.opaqueLeaf{
        	            	    msg:     "rpc error: code = PermissionDenied desc = foo",
        	            	    details: errorspb.EncodedErrorDetails{
        	            	        OriginalTypeName:  "google.golang.org/grpc/internal/status/*status.Error",
        	            	        ErrorTypeMark:     errorspb.ErrorTypeMark{FamilyName:"google.golang.org/grpc/internal/status/*status.Error", Extension:""},
        	            	        ReportablePayload: nil,
        	            	        FullDetails:       (*types.Any)(nil),
        	            	    },
        	            	})
        	Test:       	TestFoo
--- FAIL: TestFoo (0.00s)
```

```

**Comment by erikgrinaker** [comment]
Yes, mostly. It's a little bit tricker, in that `*status.Error` is actually a type alias that implements `error` but _doesn't_ implement `proto.Message` -- to get the Protobuf message, `EncodeError` would need to do something like this:

```go
if s, ok := grpcstatus.FromError(err); ok {
  payload = s.Proto()
}
```

After doing that, `DecodeError()` will fail to decode the Protobuf because the `Any` field just gets something like `type.googleapis.com/` as the type identifier, which can't be used.

**Comment by tbg** [comment]
Oh, interesting. And I'm seeing correctly that `errors.RegisterLeaf{De,En}coder` could do the transition between the `*Status` and its underlying proto, but then we still have a problem with the `Any` not being recognized properly, right?

**Comment by erikgrinaker** [comment]
Yep, we'd need to convert the Protobuf into a gogo type. We could of course do this "by hand", but I suspect retaining the detail types might get iffy with a mix of vanilla and gogo types.

**Comment by tbg** [comment]
:+1: thanks for confirming. This is indeed a pickle. I tend to think (though I'm not the authority here) that given the state of things we are more likely to move to a fork of vanilla proto rather than buy deeper into gogoproto in the future. (As far as I know, our main gripe with vanilla proto is that they've been resisting the `nullable = false` option, and we can't eat the GC overhead of making the switch to add pointers everywhere afaik).

**Comment by erikgrinaker** [comment]
Yeah, that makes sense -- I'll go with explicit gogo coding for now, and we can revisit down the line. Thanks for the input.

> our main gripe with vanilla proto is that they've been resisting the nullable = false option, and we can't eat the GC overhead of making the switch to add pointers everywhere

Ah, didn't consider the resource cost of all those pointers. FWIW, Proto 3.12 introduced [experimental support for field presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md), so there may be a solution to that with vanilla Protobuf eventually.

**Comment by erikgrinaker** [comment]
Ok @tgb, I've gotten to the point where `PermissionDenied` is propagated all the way out to `adminServer.DecommissionStatus()`.

`adminServer.Decommission()`  returns `serverpb.DecommissionStatusResponse` which is populated by `adminServer.DecommissionStatus()` after decommissioning. If we've lost access to the cluster we can't fully populate this response, since the replica counts are contained in system ranges:

https://github.com/cockroachdb/cockroach/blob/e97ef80cb281a6c71626b47428b570af37726bfc/pkg/server/admin.go#L1913-L1939

However, we expect the nodes to have been drained before marking them as decommissioned, so maybe we can just set the replica counts to 0 in this case? We may even want to enforce that replica counts are in fact 0 before marking the node as decommissioned as well.

If so, we can actually restructure the decommissioning logic in such a way that we won't need cluster RPC access at all after the final decommission status has been set. We'll still fix `PermissionDenied` propagation to avoid infinite RPC retries elsewhere, but the decommissioning logic will never end up seeing it.

**Comment by tbg** [comment]
That's a good idea, I hadn't even thought about that. Maybe we can be even more radical and say that if the decommission is done, we return an empty `DecommissionResponse`? That way we don't have to worry about populating a partial response, the contract will simply be that status updates are only emitted before the final switch being flipped. I think on the cli side all we'd need is a small change here:

https://github.com/cockroachdb/cockroach/blob/f24548e3c7dc4dcbc76259a1541b778c67098b7f/pkg/cli/node.go#L474-L480

to avoid printing the final empty proto, plus we need to convince ourselves that the previous-version cli also works against the new code. And possibly some of these tests will need massaging:

./pkg/cmd/roachtest/mixed_version_decommission.go
./pkg/cmd/roachtest/decommission.go
./pkg/cmd/roachtest/decommission_self.go

which they will anyway to account for the newfound ability to decommission yourself.

**Comment by erikgrinaker** [comment]
> Maybe we can be even more radical and say that if the decommission is done, we return an empty `DecommissionResponse`?

Right, I wasn't sure if we could break these APIs -- are all of these RPC APIs (including admin and status) considered internal? Do we specify what is and isn't subject to backwards compatibility anywhere?

In any case, I like the symmetry of returning the same response for all calls, and it shouldn't really be a problem in the current state (but might cause problems if we want additional status data later). But if you think it'd be better to just return an empty response then that's obviously even easier (unless it causes any issues with e.g. the CLI).

**Comment by knz** [comment]
How would the cli behave with the proposed different response?

**Comment by erikgrinaker** [comment]
From what I can tell, the current CLI code would simply not print the last status update (after the transition to `DECOMMISSIONED`), and exit immediately with no further output.

We could change this to print an additional status message at the end (e.g. "nodes decommissioned"), but I feel like reporting the final status in the same style as the progress status is better.

**Comment by knz** [comment]
My question was towards understanding what happens when client and server versions don't match. In this case, the issue client side is one of UX but it is not otherwise detrimental to correctness: the cli command terminates without error after the node is fully decommissioned. 

For users who care about the output display we can recommend they upgrade their CLi command to the latest version.
