### ISSUE TITLE
sql: kv txn held open while sql txn waits for ROLLBACK

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#60915]
**Is your feature request related to a problem? Please describe.**
While a SQL transaction is in aborted state (i.e. refusing commands, but waiting for explicit ROLLBACK), the corresponding KV transaction is still alive and may hold intents open.

**Describe the solution you'd like**
Ideally the KV txn would be torn down the moment it is no longer used.

**Describe alternatives you've considered**
Don't do anything

**Additional context**
Repro:

```sql
-- session 1
create table foo(v int)
begin;
insert into foo values(1)
asdasfasfasfasf
select 1 -- current txn is aborted, commands ignored until end of txn block

-- session 2
begin;
select * from foo -- blocks forever
```

Jira issue: CRDB-3103

**Comment by asubiotto** [comment]
How bad is it that this is a problem?

**Comment by asubiotto** [comment]
I assume most aborted transactions will be rolled back at some point so this is not super high priority, but we should fix this.

**Comment by tbg** [comment]
I'm not aware of this having figured prominently in any RCA. I just realized this myself during a `./cockroach demo` session the other day and thought it would be worth filing. Leaving a txn open for longer than anticipated can cause problems, and while most drivers wouldn't waste time sending the rollback *and* aborts should be rare, there is probably a situation out there in which it will make a positive difference.
For example, one possible outcome of https://github.com/cockroachdb/cockroach/issues/33007 would be that txns that try to access an unavailable range will abort immediately. Even if the SQL client does the right thing, in a geo-distributed cluster this can still add much more contention to the system than is necessary.

**Comment by andreimatei** [comment]
The reason why we're not rolling back the kv txn as soon as an error is hit is because savepoints are supposed to let you recover from the error. I believe we've discussed in the past special-casing transactions without savepoints but it didn't seem worth it. It still doesn't seem worth it to me; I personally would close.
